spring: 
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:oracleglobal
    username: SERVIEXPRESS
    password: serviexpress
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: create-drop
      generate-ddl: true
    show-sql: true