spring: 
  datasource:
    url: jdbc:mysql://mysql_server:3306/serviexpress
    username: root
    password: serviexpress
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      generate-ddl: true
    show-sql: true