spring: 
  datasource:
    url: jdbc:oracle:thin:@xe.chyuylsvwn3e.sa-east-1.rds.amazonaws.com:1521:xe
    username: SERVIEXPRESS
    password: serviexpress
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: create-drop
      generate-ddl: true
    show-sql: true